version: "3"

# docker-compose for https://github.com/dockersamples/example-voting-app
# firts create all images

services:
  # docker run -d --name vote-app -p 5000:80 --link redis:redis vote-app
  vote-app:
    image: vote-app
    ports:
      - "5000:80"
    networks:
      - front-end
      - back-end
    depends_on:
      - redis

  # docker run -d --name=redis -p 6379:6379 redis:alpine
  redis:
    image: redis:alpine
    networks:
      - back-end
    ports:
      - "6379:6379"

  # docker run -d --name=db -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres postgres:15-alpine
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - back-end
    ports:
      - "5432:5432"

  # docker run -d --name worker-app --link redis:redis --link db:db worker-app
  worker-app:
    image: worker-app
    networks:
      - back-end
    depends_on:
      - redis
      - db

  # docker run -d --name result-app -p 5001:80 -p 5858:5858 --link db:db result-app
  result-app:
    image: result-app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-end
      - back-end
    depends_on:
      - db

networks:
  front-end:
  back-end:
