# $ docker compose run

services:
  vote:
    image: vote-app
    ports:
      - 5000:80
    depends_on:
      - redis

  worker:
    image: worker-app
    depends_on:
      - db
      - redis

  result:
    image: result-app
    ports:
      - 5001:80
    depends_on:
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres